name: Develop -> Master Push CI
on:
  push:
    branches: [ master ]
jobs:
  exec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/reusable/deploy_docs.yml
      - uses: ./.github/workflows/reusable/deploy_npm.yml
