name: Develop -> Master PR CI
on:
  pull_request:
    branches: [ master ]
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
  test:
    uses: ./.github/workflows/test.yml
    needs: checkout
