name: Feature -> Develop CI
on:
  push:
    branches: [ develop ]
jobs:
  exec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/reusable/test
